project:
  type: website
  output-dir: docs

website:
  title: "Data Visualization Examples"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "floating"
    search: true
    contents: 
      - index.qmd
      - chart_bar.qmd
      - chart_beeswarm.qmd
      - chart_small-multiples.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

