---
title: "Additional Formatting Options"
---

## Additional formatting bar charts

The steps for formatting can be applied to any of the bar charts above.

### Showing the distribution of one variable

```{r add in formatting}
library(ggplot2)
library(smcepi)
library(tidyverse)
# load data
data("HairEyeColor")

# reshape the data
hair_eye_freq <- HairEyeColor %>%
  data.frame() %>%
  group_by(Hair, Eye) %>%
  summarize(freq = sum(Freq),
            .groups = "keep") %>%
  ungroup() %>%
  group_by(Hair) %>%
  mutate(total = sum(freq),
         prop = freq/total) %>%
  ungroup()

eye_overall <- hair_eye_freq %>%
  select(Eye, freq) %>%
  group_by(Eye) %>%
  summarize(freq_eye = sum(freq),
            .groups = "keep") %>%
  ungroup()

eye_overall %>%
  ggplot(aes(x = Eye, 
             y = freq_eye)) +
  geom_bar(position = "dodge",
           stat = "identity",
           fill = "#38939b") +
  geom_text(aes(x = Eye, 
                y = freq_eye,
                label = freq_eye),
    vjust = -0.1, fontface = "bold", color = "black", size = 4) +
  labs(title = "Distribution of Eye Color for all Students Surveyed") +
  theme_gg_smc()
```

```{r}
### fill by frequency ----
eye_overall %>%
  ggplot(aes(x = Eye, 
             y = freq_eye,
             fill = freq_eye)) +
  geom_bar(position = "dodge",
           stat = "identity") + 
  scale_fill_gradient(low = "white", high = "#006cb6") + 
  theme_gg_smc()

### fill with a palette ----
eye_overall %>%
  ggplot(aes(x = Eye, 
             y = freq_eye,
             fill = Eye)) +
  geom_bar(position = "dodge",
           stat = "identity") + 
  scale_fill_brewer(palette = "Spectral") + 
  theme_gg_smc()

```

### Manually assigning colors to each category category

```{r}
hair_eye_freq %>% 
  ggplot(aes(x = Hair, 
             y = freq,
             fill = Eye)) +
  geom_bar(position = "dodge",
           stat = "identity") + 
  scale_fill_manual(values = c("Brown" = "#873600",
                               "Blue" = "#0288D1",
                               "Hazel" = "#CFD8DC",
                               "Green" = "#7CB342"),
                    name = "Eye Color") + 
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(title = "Distribution of Eye Color by Hair Color") +
  xlab("Hair Color") +
  theme_gg_smc()
```

```{r}


### color based on values ---- 
hair_eye_freq %>%
    group_by(Hair) %>%
  mutate(total = sum(freq),
         prop = freq/total) %>%
  ungroup() %>%
  mutate(maj = case_when(prop > 0.5 ~ "majority",
                         TRUE ~ "minority")) %>%
  ggplot(aes(x = Hair, 
             y = freq,
             group = Eye,
             fill = maj)) +
  geom_bar(position = "dodge",
           stat = "identity",
           color = "black") +
  scale_fill_manual(values = c("majority" = "#0288D1",
                               "minority" = "#CFD8DC")) + 
  labs(title = "Frequency of Eye Color by Hair Color") + 
  theme_gg_smc()
```

------------------------------------------------------------------------
